// servers/frontend/src/pages/Chapter05Page/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { ChapterPage } from "../ChapterPage";
import CloneSection from "./components/CloneSection";
import CommonOperationsSection from "./components/CommonOperationsSection";
import CreateDirsSection from "./components/CreateDirsSection";
import DockerNetworkSection from "./components/DockerNetworkSection";
import DocsSection from "./components/DocsSection";
import EnvConfigSection from "./components/EnvConfigSection";
import IntegrateEdgeSection from "./components/IntegrateEdgeSection";
import NextStepsSection from "./components/NextStepsSection";
import PrerequisitesSection from "./components/PrerequisitesSection";
import StartServiceSection from "./components/StartServiceSection";
import VerifyConfigSection from "./components/VerifyConfigSection";
import VerifyDeploymentSection from "./components/VerifyDeploymentSection";
import WhySection from "./components/WhySection";

const Chapter05Page = memo(() => {
  const { t } = useTranslation("chapter05");

  return (
    <ChapterPage title={t("title")} intro={t("intro")} introHtml>
      <WhySection />
      <PrerequisitesSection />
      <CloneSection />
      <CreateDirsSection />
      <EnvConfigSection />
      <DockerNetworkSection />
      <VerifyConfigSection />
      <StartServiceSection />
      <VerifyDeploymentSection />
      <IntegrateEdgeSection />
      <CommonOperationsSection />
      <DocsSection />
      <NextStepsSection />
    </ChapterPage>
  );
});

Chapter05Page.displayName = "Chapter05Page";
export default Chapter05Page;

// servers/frontend/src/pages/Chapter05Page/index.vue
<template>
  <div :class="styles.container">
    <div :class="styles.header">
      <BackButton />
      <h1>{{ $t('chapter05.title') }}</h1>
    </div>
    <div :class="styles.content">
      <p :class="styles.intro" v-html="$t('chapter05.intro')"></p>

      <WhySection />
      <PrerequisitesSection />
      <CloneSection />
      <CreateDirsSection />
      <EnvConfigSection />
      <DockerNetworkSection />
      <VerifyConfigSection />
      <StartServiceSection />
      <VerifyDeploymentSection />
      <IntegrateEdgeSection />
      <CommonOperationsSection />
      <DocsSection />
      <NextStepsSection />


    </div>
  </div>
</template>

<script setup lang="ts">
import { BackButton } from '@/components'
import styles from './styles.module.css'
import WhySection from './components/WhySection/index.vue'
import PrerequisitesSection from './components/PrerequisitesSection/index.vue'
import CloneSection from './components/CloneSection/index.vue'
import CreateDirsSection from './components/CreateDirsSection/index.vue'
import EnvConfigSection from './components/EnvConfigSection/index.vue'
import DockerNetworkSection from './components/DockerNetworkSection/index.vue'
import VerifyConfigSection from './components/VerifyConfigSection/index.vue'
import StartServiceSection from './components/StartServiceSection/index.vue'
import VerifyDeploymentSection from './components/VerifyDeploymentSection/index.vue'
import IntegrateEdgeSection from './components/IntegrateEdgeSection/index.vue'
import CommonOperationsSection from './components/CommonOperationsSection/index.vue'
import DocsSection from './components/DocsSection/index.vue'
import NextStepsSection from './components/NextStepsSection/index.vue'
</script>
