// servers/frontend/src/pages/Chapter03Page/components/PasswordSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const PasswordSection = memo(() => {
  const { t } = useTranslation("chapter03");

  return (
      <section>
          <h2>{t("password.title")}</h2>

          <div>
            <h3>{t("password.strong.title")}</h3>
            <p>{t("password.strong.description")}</p>
            <ul>
              {tList(t, "password.strong.items").map((item, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
            </ul>
          </div>

          <div>
            <h3>{t("password.management.title")}</h3>
            <ul>
              {tList(t, "password.management.items").map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </section>
  );
});

PasswordSection.displayName = "PasswordSection";
export default PasswordSection;

// servers/frontend/src/pages/Chapter03Page/components/PasswordSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter03.password.title') }}</h2>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter03.password.strong.title') }}</h3>
      <p>{{ $t('chapter03.password.strong.description') }}</p>
      <ul>
        <li v-for="(item, index) in $tm('chapter03.password.strong.items')" :key="index" v-html="item"></li>
      </ul>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter03.password.management.title') }}</h3>
      <ul>
        <li v-for="(item, index) in $tm('chapter03.password.management.items')" :key="index">
          {{ item }}
        </li>
      </ul>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
