// servers/frontend/src/pages/HomePage/index.tsx
import { memo } from "react";
import { Link } from "react-router";
import { useTranslation } from "react-i18next";
import { Button, Card, Container, Flex, Heading, Text } from "nfx-ui/components";
import { PageFrame } from "nfx-ui/layouts";

import { FileText } from "@/assets/icons/lucide";
import { chapterPath } from "@/navigations";
import { chapterLocale } from "@/utils/i18nContent";

const CHAPTER_KEYS = ["chapter01", "chapter02", "chapter03", "chapter04", "chapter05"] as const;

const HomePage = memo(() => {
  const { t, i18n } = useTranslation("common");
  const locale = chapterLocale(i18n.language);

  const chapters = CHAPTER_KEYS.map((key) => ({
    id: t(`chapterList.${key}.id`),
    title: t(`chapterList.${key}.title`),
  }));

  return (
    <PageFrame>
      <Container size="3" py="6">
        <Flex direction="column" gap="6" align="center">
          <Flex direction="column" gap="2" align="center">
            <Heading size="8">{t("title")}</Heading>
            <Text as="p" size="4" color="gray" align="center">
              {t("subtitle")}
            </Text>
          </Flex>
          <Card size="3" style={{ width: "100%", maxWidth: 640 }}>
            <Flex direction="column" gap="3">
              <Heading size="5">{t("chapters.title")}</Heading>
              {chapters.map((chapter) => (
                <Button key={chapter.id} variant="soft" size="3" asChild>
                  <Link to={chapterPath(locale, chapter.id)}>
                    <FileText size={18} />
                    {chapter.title}
                  </Link>
                </Button>
              ))}
            </Flex>
          </Card>
        </Flex>
      </Container>
    </PageFrame>
  );
});

HomePage.displayName = "HomePage";
export default HomePage;

// servers/frontend/src/pages/HomePage/index.vue
<template>
  <div :class="styles.home">
    <header :class="styles.header">
      <h1>{{ $t('common.title') }}</h1>
      <p>{{ $t('common.subtitle') }}</p>
    </header>
    <main :class="styles.main">
      <section :class="styles.chapters">
        <h2>{{ $t('common.chapters.title') }}</h2>
        <ul>
          <li v-for="chapter in chapters" :key="chapter.id">
            <router-link :to="`/${locale}/${chapter.id}`">
              <BookOpen :size="20" :class="styles.icon" />
              <span>{{ chapter.title }}</span>
            </router-link>
          </li>
        </ul>
      </section>
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { BookOpen } from 'lucide-vue-next'
import styles from './styles.module.css'

const { t, locale } = useI18n()

const chapters = computed(() => [
  {
    id: t('common.chapterList.chapter01.id'),
    title: t('common.chapterList.chapter01.title'),
  },
  {
    id: t('common.chapterList.chapter02.id'),
    title: t('common.chapterList.chapter02.title'),
  },
  {
    id: t('common.chapterList.chapter03.id'),
    title: t('common.chapterList.chapter03.title'),
  },
  {
    id: t('common.chapterList.chapter04.id'),
    title: t('common.chapterList.chapter04.title'),
  },
  {
    id: t('common.chapterList.chapter05.id'),
    title: t('common.chapterList.chapter05.title'),
  },
])
</script>
