// servers/frontend/src/pages/Chapter03Page/components/CloneSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const CloneSection = memo(() => {
  const { t } = useTranslation("chapter03");

  return (
      <section>
          <h2>{t("clone.title")}</h2>
          <p>{t("clone.description")}</p>

          <div>
            <h3>{t("clone.step1.title")}</h3>
            <p>{t("clone.step1.description")}</p>
            <pre><code>{t("clone.step1.command")}</code></pre>
            <ul>
              {tList(t, "clone.step1.notes").map((note, index) => (
                <li key={index}>{note}</li>
              ))}
            </ul>
          </div>

          <div>
            <h3>{t("clone.step2.title")}</h3>
            <p dangerouslySetInnerHTML={{ __html: t("clone.step2.description") }} />
            <pre><code>{t("clone.step2.command")}</code></pre>
            <ul>
              {tList(t, "clone.step2.notes").map((note, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: note }} />
              ))}
            </ul>
            <div>
              <h4>{t("clone.step2.optional.title")}</h4>
              <p>{t("clone.step2.optional.description")}</p>
              {tList(t, "clone.step2.optional.commands").map((cmd, index) => (
              <pre key={index}><code>{cmd}</code></pre>
            ))}
            </div>
          </div>

          <div>
            <h3>{t("clone.step3.title")}</h3>
            <pre><code>{t("clone.step3.command")}</code></pre>
          </div>
        </section>
  );
});

CloneSection.displayName = "CloneSection";
export default CloneSection;

// servers/frontend/src/pages/Chapter03Page/components/CloneSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter03.clone.title') }}</h2>
    <p>{{ $t('chapter03.clone.description') }}</p>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter03.clone.step1.title') }}</h3>
      <p>{{ $t('chapter03.clone.step1.description') }}</p>
      <pre><code>{{ $t('chapter03.clone.step1.command') }}</code></pre>
      <ul>
        <li v-for="(note, index) in $tm('chapter03.clone.step1.notes')" :key="index">
          {{ note }}
        </li>
      </ul>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter03.clone.step2.title') }}</h3>
      <p v-html="$t('chapter03.clone.step2.description')"></p>
      <pre><code>{{ $t('chapter03.clone.step2.command') }}</code></pre>
      <ul>
        <li v-for="(note, index) in $tm('chapter03.clone.step2.notes')" :key="index" v-html="note"></li>
      </ul>
      <div :class="styles.nested">
        <h4>{{ $t('chapter03.clone.step2.optional.title') }}</h4>
        <p>{{ $t('chapter03.clone.step2.optional.description') }}</p>
        <pre v-for="(cmd, index) in $tm('chapter03.clone.step2.optional.commands')" :key="index"><code>{{ cmd }}</code></pre>
      </div>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter03.clone.step3.title') }}</h3>
      <pre><code>{{ $t('chapter03.clone.step3.command') }}</code></pre>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
