// servers/frontend/src/pages/AboutPage/index.vue
<template>
  <div :class="styles.container">
    <header :class="styles.header">
      <h1>{{ $t('about.title') }}</h1>
      <p>{{ $t('about.subtitle') }}</p>
    </header>

    <section :class="styles.section">
      <h2>{{ $t('about.what.title') }}</h2>
      <p v-html="$t('about.what.description')"></p>
    </section>

    <section :class="styles.section">
      <h2>{{ $t('about.ecosystem.title') }}</h2>
      <p v-html="$t('about.ecosystem.description')"></p>
      <ul>
        <li v-for="(item, index) in $tm('about.ecosystem.items')" :key="index" v-html="item"></li>
      </ul>
    </section>

    <section :class="styles.section">
      <h2>{{ $t('about.contribute.title') }}</h2>
      <p v-html="$t('about.contribute.description')"></p>
    </section>
  </div>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/AboutPage/index.tsx
import type { ReactNode } from "react";

import { memo } from "react";
import { Container, Flex, Heading, Section, Text } from "@radix-ui/themes";
import { useTranslation } from "react-i18next";

import { Html, PageIntro } from "@/components";

import styles from "./s.module.css";

const AboutPage = memo(() => {
  const { t } = useTranslation("about");
  const items = t("ecosystem.items", { returnObjects: true });
  const ecosystemItems = Array.isArray(items) ? items.map(String) : [];

  return (
    <Section size="2" py="6" className={styles.page}>
      <Container px="5">
        <Flex direction="column" gap="6">
          <PageIntro title={t("title")}>
            <Text as="p" size="4" color="gray">
              {t("subtitle")}
            </Text>
          </PageIntro>

          <AboutBlock title={t("what.title")}>
            <Text as="p" color="gray">
              <Html html={t("what.description")} />
            </Text>
          </AboutBlock>

          <AboutBlock title={t("ecosystem.title")}>
            <Text as="p" color="gray">
              <Html html={t("ecosystem.description")} />
            </Text>
            <Container pl="5">
              <ul className={styles.flush}>
                {ecosystemItems.map((item) => (
                  <Html as="li" key={item} html={item} />
                ))}
              </ul>
            </Container>
          </AboutBlock>

          <AboutBlock title={t("contribute.title")}>
            <Text as="p" color="gray">
              <Html html={t("contribute.description")} />
            </Text>
          </AboutBlock>
        </Flex>
      </Container>
    </Section>
  );
});

function AboutBlock({ title, children }: { title: string; children: ReactNode }) {
  return (
    <Section size="1" py="4" className={styles.block}>
      <Flex direction="column" gap="2">
        <Heading size="5">{title}</Heading>
        {children}
      </Flex>
    </Section>
  );
}

AboutPage.displayName = "AboutPage";
export default AboutPage;
