// servers/frontend/src/pages/Chapter01Page/components/RouterAccessSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const RouterAccessSection = memo(() => {
  const { t } = useTranslation("chapter01");

  return (
      <div>
          <h3>{t("router.access.title")}</h3>
          <p>{t("router.access.description")}</p>
          <ul>
            {tList(t, "router.access.items").map((item, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
          </ul>
          <img src={t("router.access.image")} alt={t("router.access.imageAlt")} />
        </div>
  );
});

RouterAccessSection.displayName = "RouterAccessSection";
export default RouterAccessSection;

// servers/frontend/src/pages/Chapter01Page/components/RouterAccessSection/index.vue
<template>
  <div :class="styles.subsection">
    <h3>{{ $t('chapter01.router.access.title') }}</h3>
    <p>{{ $t('chapter01.router.access.description') }}</p>
    <ul>
      <li v-for="(item, index) in $tm('chapter01.router.access.items')" :key="index" v-html="item"></li>
    </ul>
    <img :src="$t('chapter01.router.access.image')" :alt="$t('chapter01.router.access.imageAlt')" :class="styles.image" />
  </div>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
