// servers/frontend/src/pages/Chapter01Page/index.vue
<template>
  <div :class="styles.container">
    <div :class="styles.header">
      <BackButton />
      <h1>{{ $t('chapter01.title') }}</h1>
    </div>
    <div :class="styles.content">
      <p :class="styles.intro">{{ $t('chapter01.intro') }}</p>

      <PrerequisitesSection />
      <RouterConfigSection />
      <SecurityStrategySection />

      <!-- Conclusion -->
      <section :class="styles.conclusionSection">
        <p v-html="$t('chapter01.conclusion')"></p>
      </section>

      <!-- Next Chapter Button -->
      <div :class="styles.nextButtonContainer">
        <NextPageButton 
          v-if="$t('chapter01.nextChapterPath')"
          :to="`/${locale}/${$t('chapter01.nextChapterPath')}`"
          :text="$t('chapter01.nextChapterText')"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { BackButton, NextPageButton } from '@/components'
import styles from './styles.module.css'
import PrerequisitesSection from './components/PrerequisitesSection/index.vue'
import RouterConfigSection from './components/RouterConfigSection/index.vue'
import SecurityStrategySection from './components/SecurityStrategySection/index.vue'

const { locale } = useI18n()
</script>

// servers/frontend/src/pages/Chapter01Page/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { chapterLocale } from "@/utils/i18nContent";

import { ChapterPage } from "../ChapterPage";
import PrerequisitesSection from "./components/PrerequisitesSection";
import RouterConfigSection from "./components/RouterConfigSection";
import SecurityStrategySection from "./components/SecurityStrategySection";

const Chapter01Page = memo(() => {
  const { t, i18n } = useTranslation("chapter01");
  const locale = chapterLocale(i18n.language);
  const nextPath = t("nextChapterPath");

  return (
    <ChapterPage
      title={t("title")}
      intro={t("intro")}
      nextTo={nextPath ? `/${locale}/${nextPath}` : undefined}
      nextText={t("nextChapterText")}
    >
      <PrerequisitesSection />
      <RouterConfigSection />
      <SecurityStrategySection />
    </ChapterPage>
  );
});

Chapter01Page.displayName = "Chapter01Page";
export default Chapter01Page;
