// servers/frontend/src/pages/Chapter03Page/components/OtherConfigSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter03.otherConfig.title') }}</h2>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter03.otherConfig.kafka.title') }}</h3>
      <p v-html="$t('chapter03.otherConfig.kafka.description')"></p>
      <ul>
        <li v-for="(item, index) in $tm('chapter03.otherConfig.kafka.items')" :key="index">
          {{ item }}
        </li>
      </ul>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter03Page/components/OtherConfigSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const OtherConfigSection = memo(() => {
  const { t } = useTranslation("chapter03");

  return (
      <section>
          <h2>{t("otherConfig.title")}</h2>

          <div>
            <h3>{t("otherConfig.kafka.title")}</h3>
            <p dangerouslySetInnerHTML={{ __html: t("otherConfig.kafka.description") }} />
            <ul>
              {tList(t, "otherConfig.kafka.items").map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </section>
  );
});

OtherConfigSection.displayName = "OtherConfigSection";
export default OtherConfigSection;
