// servers/frontend/src/pages/Chapter03Page/components/DocsSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const DocsSection = memo(() => {
  const { t } = useTranslation("chapter03");

  return (
      <section>
          <h2>{t("docs.title")}</h2>
          <p dangerouslySetInnerHTML={{ __html: t("docs.description") }} />
          <ul>
            {tList(t, "docs.items").map((item, index) => (
                <li key={index}>{item}</li>
              ))}
          </ul>
          <p>{t("docs.note")}</p>
        </section>
  );
});

DocsSection.displayName = "DocsSection";
export default DocsSection;

// servers/frontend/src/pages/Chapter03Page/components/DocsSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter03.docs.title') }}</h2>
    <p v-html="$t('chapter03.docs.description')"></p>
    <ul>
      <li v-for="(item, index) in $tm('chapter03.docs.items')" :key="index">
        {{ item }}
      </li>
    </ul>
    <p>{{ $t('chapter03.docs.note') }}</p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
