// servers/frontend/src/pages/Chapter05Page/components/DockerNetworkSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter05.dockerNetwork.title') }}</h2>
    <p>{{ $t('chapter05.dockerNetwork.description') }}</p>
    <p>{{ $t('chapter05.dockerNetwork.description2') }}</p>
    <pre><code>{{ $t('chapter05.dockerNetwork.command') }}</code></pre>
    <p>{{ $t('chapter05.dockerNetwork.description3') }}</p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter05Page/components/DockerNetworkSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


const DockerNetworkSection = memo(() => {
  const { t } = useTranslation("chapter05");

  return (
    <section>
      <h2>{t("dockerNetwork.title")}</h2>
      <p>{t("dockerNetwork.description")}</p>
      <p>{t("dockerNetwork.description2")}</p>
      <pre>
        <code>{t("dockerNetwork.command")}</code>
      </pre>
      <p>{t("dockerNetwork.description3")}</p>
    </section>
  );
});

DockerNetworkSection.displayName = "DockerNetworkSection";
export default DockerNetworkSection;
