// servers/frontend/src/pages/Chapter01Page/components/RouterConfigSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter01.router.title') }}</h2>
    <p>{{ $t('chapter01.router.intro') }}</p>

    <RouterAccessSection />
    <FirewallConfigSection />
    <PortForwardingSection />
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
import RouterAccessSection from '../RouterAccessSection/index.vue'
import FirewallConfigSection from '../FirewallConfigSection/index.vue'
import PortForwardingSection from '../PortForwardingSection/index.vue'
</script>

// servers/frontend/src/pages/Chapter01Page/components/RouterConfigSection/index.tsx
import { memo } from "react";
import RouterAccessSection from "../RouterAccessSection";
import FirewallConfigSection from "../FirewallConfigSection";
import PortForwardingSection from "../PortForwardingSection";

import { useTranslation } from "react-i18next";


const RouterConfigSection = memo(() => {
  const { t } = useTranslation("chapter01");

  return (
      <section>
          <h2>{t("router.title")}</h2>
          <p>{t("router.intro")}</p>

          <RouterAccessSection />
          <FirewallConfigSection />
          <PortForwardingSection />
        </section>
  );
});

RouterConfigSection.displayName = "RouterConfigSection";
export default RouterConfigSection;
