// servers/frontend/src/pages/Chapter05Page/components/CreateDirsSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


const CreateDirsSection = memo(() => {
  const { t } = useTranslation("chapter05");

  return (
    <section>
      <h2>{t("createDirs.title")}</h2>
      <p>{t("createDirs.description")}</p>
      <p>{t("createDirs.description2")}</p>
      <p>{t("createDirs.description3")}</p>
      <pre>
        <code>{t("createDirs.command")}</code>
      </pre>
      <p>{t("createDirs.permissions")}</p>
    </section>
  );
});

CreateDirsSection.displayName = "CreateDirsSection";
export default CreateDirsSection;

// servers/frontend/src/pages/Chapter05Page/components/CreateDirsSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter05.createDirs.title') }}</h2>
    <p>{{ $t('chapter05.createDirs.description') }}</p>
    <p>{{ $t('chapter05.createDirs.description2') }}</p>
    <p>{{ $t('chapter05.createDirs.description3') }}</p>
    <pre><code>{{ $t('chapter05.createDirs.command') }}</code></pre>
    <p>{{ $t('chapter05.createDirs.permissions') }}</p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
