// servers/frontend/src/pages/Chapter03Page/components/VerifySection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter03.verify.title') }}</h2>
    <p>{{ $t('chapter03.verify.description') }}</p>
    <ol>
      <li v-for="(item, index) in $tm('chapter03.verify.items')" :key="index" v-html="item"></li>
    </ol>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter03Page/components/VerifySection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const VerifySection = memo(() => {
  const { t } = useTranslation("chapter03");

  return (
      <section>
          <h2>{t("verify.title")}</h2>
          <p>{t("verify.description")}</p>
          <ol>
            {tList(t, "verify.items").map((item, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
          </ol>
        </section>
  );
});

VerifySection.displayName = "VerifySection";
export default VerifySection;
