// servers/frontend/src/pages/Chapter02Page/components/ChecklistSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const ChecklistSection = memo(() => {
  const { t } = useTranslation("chapter02");

  return (
      <section>
          <h2>{t("checklist.title")}</h2>
          <p>{t("checklist.description")}</p>
          <ul>
            {tList(t, "checklist.items").map((item, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
          </ul>
          <p dangerouslySetInnerHTML={{ __html: t("checklist.conclusion") }} />
        </section>
  );
});

ChecklistSection.displayName = "ChecklistSection";
export default ChecklistSection;

// servers/frontend/src/pages/Chapter02Page/components/ChecklistSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter02.checklist.title') }}</h2>
    <p>{{ $t('chapter02.checklist.description') }}</p>
    <ul :class="styles.checklist">
      <li v-for="(item, index) in $tm('chapter02.checklist.items')" :key="index" v-html="item"></li>
    </ul>
    <p v-html="$t('chapter02.checklist.conclusion')"></p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
