// servers/frontend/src/pages/Chapter02Page/components/SSHSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const SSHSection = memo(() => {
  const { t } = useTranslation("chapter02");

  return (
      <section>
          <h2>{t("ssh.title")}</h2>
          <p>{t("ssh.description")}</p>
          <img src={t("ssh.image")} alt={t("ssh.imageAlt")} />

          <div>
            <h3>{t("ssh.steps.title")}</h3>
            <ol>
              {tList(t, "ssh.steps.items").map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </div>

          <div>
            <h3>{t("ssh.security.title")}</h3>
            <ul>
              {tList(t, "ssh.security.items").map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </section>
  );
});

SSHSection.displayName = "SSHSection";
export default SSHSection;

// servers/frontend/src/pages/Chapter02Page/components/SSHSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter02.ssh.title') }}</h2>
    <p>{{ $t('chapter02.ssh.description') }}</p>
    <img :src="$t('chapter02.ssh.image')" :alt="$t('chapter02.ssh.imageAlt')" :class="styles.image" />

    <div :class="styles.subsection">
      <h3>{{ $t('chapter02.ssh.steps.title') }}</h3>
      <ol>
        <li v-for="(step, index) in $tm('chapter02.ssh.steps.items')" :key="index">
          {{ step }}
        </li>
      </ol>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter02.ssh.security.title') }}</h3>
      <ul>
        <li v-for="(item, index) in $tm('chapter02.ssh.security.items')" :key="index">
          {{ item }}
        </li>
      </ul>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
