// servers/frontend/src/pages/Chapter05Page/components/VerifyConfigSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { tList } from "@/utils/i18nContent";


const VerifyConfigSection = memo(() => {
  const { t } = useTranslation("chapter05");

  return (
    <section>
      <h2>{t("verifyConfig.title")}</h2>
      <p>{t("verifyConfig.description")}</p>
      <ul>
        {tList(t, "verifyConfig.checks").map((check, index) => (
          <li key={index} dangerouslySetInnerHTML={{ __html: check }} />
        ))}
      </ul>
    </section>
  );
});

VerifyConfigSection.displayName = "VerifyConfigSection";
export default VerifyConfigSection;

// servers/frontend/src/pages/Chapter05Page/components/VerifyConfigSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter05.verifyConfig.title') }}</h2>
    <p>{{ $t('chapter05.verifyConfig.description') }}</p>

    <ul>
      <li v-for="(check, index) in $tm('chapter05.verifyConfig.checks')" :key="index" v-html="check"></li>
    </ul>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
