// servers/frontend/src/pages/Chapter02Page/components/WebCenterSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter02.webCenter.title') }}</h2>
    <p v-html="$t('chapter02.webCenter.important')"></p>
    <img :src="$t('chapter02.webCenter.image')" :alt="$t('chapter02.webCenter.imageAlt')" :class="styles.image" />

    <div :class="styles.subsection">
      <h3>{{ $t('chapter02.webCenter.why.title') }}</h3>
      <p>{{ $t('chapter02.webCenter.why.description') }}</p>
      <ul>
        <li v-for="(port, index) in $tm('chapter02.webCenter.why.ports')" :key="index" v-html="port"></li>
      </ul>
      <p v-html="$t('chapter02.webCenter.why.conflict')"></p>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter02.webCenter.steps.title') }}</h3>
      <ol>
        <li v-for="(step, index) in $tm('chapter02.webCenter.steps.items')" :key="index">
          {{ step }}
        </li>
      </ol>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter02Page/components/WebCenterSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const WebCenterSection = memo(() => {
  const { t } = useTranslation("chapter02");

  return (
      <section>
          <h2>{t("webCenter.title")}</h2>
          <p dangerouslySetInnerHTML={{ __html: t("webCenter.important") }} />
          <img src={t("webCenter.image")} alt={t("webCenter.imageAlt")} />

          <div>
            <h3>{t("webCenter.why.title")}</h3>
            <p>{t("webCenter.why.description")}</p>
            <ul>
              {tList(t, "webCenter.why.ports").map((port, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: port }} />
              ))}
            </ul>
            <p dangerouslySetInnerHTML={{ __html: t("webCenter.why.conflict") }} />
          </div>

          <div>
            <h3>{t("webCenter.steps.title")}</h3>
            <ol>
              {tList(t, "webCenter.steps.items").map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </div>
        </section>
  );
});

WebCenterSection.displayName = "WebCenterSection";
export default WebCenterSection;
