// servers/frontend/src/pages/Chapter02Page/components/ApplicationsSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter02.applications.title') }}</h2>
    <p>{{ $t('chapter02.applications.description') }}</p>
    <img :src="$t('chapter02.applications.image')" :alt="$t('chapter02.applications.imageAlt')" :class="styles.image" />

    <div :class="styles.subsection">
      <h3>{{ $t('chapter02.applications.list.title') }}</h3>
      
      <div :class="styles.appItem">
        <h4>{{ $t('chapter02.applications.list.docker.name') }}</h4>
        <p><strong>{{ $t('chapter02.applications.list.docker.purpose') }}</strong>：{{ $t('chapter02.applications.list.docker.description') }}</p>
        <p>{{ $t('chapter02.applications.list.docker.version') }}</p>
        <p><code>{{ $t('chapter02.applications.list.docker.verify') }}</code></p>
      </div>

      <div :class="styles.appItem">
        <h4>{{ $t('chapter02.applications.list.git.name') }}</h4>
        <p><strong>{{ $t('chapter02.applications.list.git.purpose') }}</strong>：{{ $t('chapter02.applications.list.git.description') }}</p>
        <p><code>{{ $t('chapter02.applications.list.git.verify') }}</code></p>
      </div>

      <div :class="styles.appItem">
        <h4>{{ $t('chapter02.applications.list.entware.name') }}</h4>
        <p><strong>{{ $t('chapter02.applications.list.entware.purpose') }}</strong>：{{ $t('chapter02.applications.list.entware.description') }}</p>
        <p><code>{{ $t('chapter02.applications.list.entware.verify') }}</code></p>
        <p><strong>{{ $t('chapter02.applications.list.entware.importance') }}</strong></p>
      </div>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter02.applications.order.title') }}</h3>
      <ol>
        <li v-for="(item, index) in $tm('chapter02.applications.order.items')" :key="index" v-html="item"></li>
      </ol>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter02Page/components/ApplicationsSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const ApplicationsSection = memo(() => {
  const { t } = useTranslation("chapter02");

  return (
      <section>
          <h2>{t("applications.title")}</h2>
          <p>{t("applications.description")}</p>
          <img src={t("applications.image")} alt={t("applications.imageAlt")} />

          <div>
            <h3>{t("applications.list.title")}</h3>
            
            <div>
              <h4>{t("applications.list.docker.name")}</h4>
              <p><strong>{t("applications.list.docker.purpose")}</strong>：{t("applications.list.docker.description")}</p>
              <p>{t("applications.list.docker.version")}</p>
              <p><code>{t("applications.list.docker.verify")}</code></p>
            </div>

            <div>
              <h4>{t("applications.list.git.name")}</h4>
              <p><strong>{t("applications.list.git.purpose")}</strong>：{t("applications.list.git.description")}</p>
              <p><code>{t("applications.list.git.verify")}</code></p>
            </div>

            <div>
              <h4>{t("applications.list.entware.name")}</h4>
              <p><strong>{t("applications.list.entware.purpose")}</strong>：{t("applications.list.entware.description")}</p>
              <p><code>{t("applications.list.entware.verify")}</code></p>
              <p><strong>{t("applications.list.entware.importance")}</strong></p>
            </div>
          </div>

          <div>
            <h3>{t("applications.order.title")}</h3>
            <ol>
              {tList(t, "applications.order.items").map((item, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
            </ol>
          </div>
        </section>
  );
});

ApplicationsSection.displayName = "ApplicationsSection";
export default ApplicationsSection;
