// servers/frontend/src/pages/Chapter01Page/components/PrerequisitesSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter01.prerequisites.title') }}</h2>
    <p>{{ $t('chapter01.prerequisites.description') }}</p>
    
    <div :class="styles.subsection">
      <h3>{{ $t('chapter01.prerequisites.network.title') }}</h3>
      <ul>
        <li v-for="(item, index) in $tm('chapter01.prerequisites.network.items')" :key="index">
          {{ item }}
        </li>
      </ul>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter01.prerequisites.china.title') }}</h3>
      <ul>
        <li v-for="(item, index) in $tm('chapter01.prerequisites.china.items')" :key="index">
          {{ item }}
        </li>
      </ul>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter01.prerequisites.other.title') }}</h3>
      <ul>
        <li v-for="(item, index) in $tm('chapter01.prerequisites.other.items')" :key="index">
          {{ item }}
        </li>
      </ul>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter01Page/components/PrerequisitesSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const PrerequisitesSection = memo(() => {
  const { t } = useTranslation("chapter01");

  return (
      <section>
          <h2>{t("prerequisites.title")}</h2>
          <p>{t("prerequisites.description")}</p>
          
          <div>
            <h3>{t("prerequisites.network.title")}</h3>
            <ul>
              {tList(t, "prerequisites.network.items").map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>

          <div>
            <h3>{t("prerequisites.china.title")}</h3>
            <ul>
              {tList(t, "prerequisites.china.items").map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>

          <div>
            <h3>{t("prerequisites.other.title")}</h3>
            <ul>
              {tList(t, "prerequisites.other.items").map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ul>
          </div>
        </section>
  );
});

PrerequisitesSection.displayName = "PrerequisitesSection";
export default PrerequisitesSection;
