// servers/frontend/src/pages/Chapter02Page/index.vue
<template>
  <div :class="styles.container">
    <div :class="styles.header">
      <BackButton />
      <h1>{{ $t('chapter02.title') }}</h1>
    </div>
    <div :class="styles.content">
      <p :class="styles.intro">{{ $t('chapter02.intro') }}</p>

      <WebCenterSection />
      <SSHSection />
      <ApplicationsSection />
      <BashConfigSection />
      <SSHClientsSection />
      <ChecklistSection />

      <!-- Next Chapter Button -->
      <div :class="styles.nextButtonContainer">
        <NextPageButton 
          v-if="$t('chapter02.nextChapterPath')"
          :to="`/${locale}/${$t('chapter02.nextChapterPath')}`"
          :text="$t('chapter02.nextChapterText')"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { BackButton, NextPageButton } from '@/components'
import styles from './styles.module.css'
import WebCenterSection from './components/WebCenterSection/index.vue'
import SSHSection from './components/SSHSection/index.vue'
import ApplicationsSection from './components/ApplicationsSection/index.vue'
import BashConfigSection from './components/BashConfigSection/index.vue'
import SSHClientsSection from './components/SSHClientsSection/index.vue'
import ChecklistSection from './components/ChecklistSection/index.vue'

const { locale } = useI18n()
</script>

// servers/frontend/src/pages/Chapter02Page/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { chapterLocale } from "@/utils/i18nContent";

import { ChapterPage } from "../ChapterPage";
import ApplicationsSection from "./components/ApplicationsSection";
import BashConfigSection from "./components/BashConfigSection";
import ChecklistSection from "./components/ChecklistSection";
import SSHClientsSection from "./components/SSHClientsSection";
import SSHSection from "./components/SSHSection";
import WebCenterSection from "./components/WebCenterSection";

const Chapter02Page = memo(() => {
  const { t, i18n } = useTranslation("chapter02");
  const locale = chapterLocale(i18n.language);
  const nextPath = t("nextChapterPath");

  return (
    <ChapterPage
      title={t("title")}
      intro={t("intro")}
      nextTo={nextPath ? `/${locale}/${nextPath}` : undefined}
      nextText={t("nextChapterText")}
    >
      <WebCenterSection />
      <SSHSection />
      <ApplicationsSection />
      <BashConfigSection />
      <SSHClientsSection />
      <ChecklistSection />
    </ChapterPage>
  );
});

Chapter02Page.displayName = "Chapter02Page";
export default Chapter02Page;
