// servers/frontend/src/pages/Chapter04Page/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { chapterLocale } from "@/utils/i18nContent";

import { ChapterPage } from "../ChapterPage";
import AddNewSiteSection from "./components/AddNewSiteSection";
import CertificatesSection from "./components/CertificatesSection";
import CloneSection from "./components/CloneSection";
import CommonOperationsSection from "./components/CommonOperationsSection";
import ConfigFilesSection from "./components/ConfigFilesSection";
import DockerComposeSection from "./components/DockerComposeSection";
import DocsSection from "./components/DocsSection";
import NextStepsSection from "./components/NextStepsSection";
import PrerequisitesSection from "./components/PrerequisitesSection";
import StartServiceSection from "./components/StartServiceSection";
import VerifyConfigSection from "./components/VerifyConfigSection";
import VerifyDeploymentSection from "./components/VerifyDeploymentSection";
import WhySection from "./components/WhySection";

const Chapter04Page = memo(() => {
  const { t, i18n } = useTranslation("chapter04");
  const locale = chapterLocale(i18n.language);
  const nextPath = t("nextChapterPath");

  return (
    <ChapterPage
      title={t("title")}
      intro={t("intro")}
      introHtml
      nextTo={nextPath ? `/${locale}/${nextPath}` : undefined}
      nextText={t("nextChapterText")}
    >
      <WhySection />
      <PrerequisitesSection />
      <CloneSection />
      <ConfigFilesSection />
      <DockerComposeSection />
      <CertificatesSection />
      <VerifyConfigSection />
      <StartServiceSection />
      <VerifyDeploymentSection />
      <AddNewSiteSection />
      <CommonOperationsSection />
      <DocsSection />
      <NextStepsSection />
    </ChapterPage>
  );
});

Chapter04Page.displayName = "Chapter04Page";
export default Chapter04Page;

// servers/frontend/src/pages/Chapter04Page/index.vue
<template>
  <div :class="styles.container">
    <div :class="styles.header">
      <BackButton />
      <h1>{{ $t('chapter04.title') }}</h1>
    </div>
    <div :class="styles.content">
      <p :class="styles.intro" v-html="$t('chapter04.intro')"></p>

      <WhySection />
      <PrerequisitesSection />
      <CloneSection />
      <ConfigFilesSection />
      <DockerComposeSection />
      <CertificatesSection />
      <VerifyConfigSection />
      <StartServiceSection />
      <VerifyDeploymentSection />
      <AddNewSiteSection />
      <CommonOperationsSection />
      <DocsSection />
      <NextStepsSection />

      <!-- Next Chapter Button -->
      <div :class="styles.nextButtonContainer">
        <NextPageButton 
          v-if="$t('chapter04.nextChapterPath')"
          :to="`/${locale}/${$t('chapter04.nextChapterPath')}`"
          :text="$t('chapter04.nextChapterText')"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { BackButton, NextPageButton } from '@/components'
import styles from './styles.module.css'
import WhySection from './components/WhySection/index.vue'
import PrerequisitesSection from './components/PrerequisitesSection/index.vue'
import CloneSection from './components/CloneSection/index.vue'
import ConfigFilesSection from './components/ConfigFilesSection/index.vue'
import DockerComposeSection from './components/DockerComposeSection/index.vue'
import CertificatesSection from './components/CertificatesSection/index.vue'
import VerifyConfigSection from './components/VerifyConfigSection/index.vue'
import StartServiceSection from './components/StartServiceSection/index.vue'
import VerifyDeploymentSection from './components/VerifyDeploymentSection/index.vue'
import AddNewSiteSection from './components/AddNewSiteSection/index.vue'
import CommonOperationsSection from './components/CommonOperationsSection/index.vue'
import DocsSection from './components/DocsSection/index.vue'
import NextStepsSection from './components/NextStepsSection/index.vue'

const { locale } = useI18n()
</script>
