// servers/frontend/src/pages/Chapter04Page/components/DocsSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter04.docs.title') }}</h2>
    <p v-html="$t('chapter04.docs.description')"></p>
    <p v-html="$t('chapter04.docs.description2')"></p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter04Page/components/DocsSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


const DocsSection = memo(() => {
  const { t } = useTranslation("chapter04");

  return (
    <section>
      <h2>{t("docs.title")}</h2>
      <p dangerouslySetInnerHTML={{ __html: t("docs.description") }} />
      <p dangerouslySetInnerHTML={{ __html: t("docs.description2") }} />
    </section>
  );
});

DocsSection.displayName = "DocsSection";
export default DocsSection;
