// servers/frontend/src/pages/Chapter03Page/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { chapterLocale } from "@/utils/i18nContent";

import { ChapterPage } from "../ChapterPage";
import CloneSection from "./components/CloneSection";
import DataPathSection from "./components/DataPathSection";
import DocsSection from "./components/DocsSection";
import EnvConfigSection from "./components/EnvConfigSection";
import IPPortSection from "./components/IPPortSection";
import NextStepsSection from "./components/NextStepsSection";
import OtherConfigSection from "./components/OtherConfigSection";
import PasswordSection from "./components/PasswordSection";
import VerifySection from "./components/VerifySection";
import WhySection from "./components/WhySection";

const Chapter03Page = memo(() => {
  const { t, i18n } = useTranslation("chapter03");
  const locale = chapterLocale(i18n.language);
  const nextPath = t("nextChapterPath");

  return (
    <ChapterPage
      title={t("title")}
      intro={t("intro")}
      introHtml
      nextTo={nextPath ? `/${locale}/${nextPath}` : undefined}
      nextText={t("nextChapterText")}
    >
      <WhySection />
      <CloneSection />
      <EnvConfigSection />
      <IPPortSection />
      <DataPathSection />
      <PasswordSection />
      <OtherConfigSection />
      <VerifySection />
      <DocsSection />
      <NextStepsSection />
    </ChapterPage>
  );
});

Chapter03Page.displayName = "Chapter03Page";
export default Chapter03Page;

// servers/frontend/src/pages/Chapter03Page/index.vue
<template>
  <div :class="styles.container">
    <div :class="styles.header">
      <BackButton />
      <h1>{{ $t('chapter03.title') }}</h1>
    </div>
    <div :class="styles.content">
      <p :class="styles.intro" v-html="$t('chapter03.intro')"></p>

      <WhySection />
      <CloneSection />
      <EnvConfigSection />
      <IPPortSection />
      <DataPathSection />
      <PasswordSection />
      <OtherConfigSection />
      <VerifySection />
      <DocsSection />
      <NextStepsSection />

      <!-- Next Chapter Button -->
      <div :class="styles.nextButtonContainer">
        <NextPageButton 
          v-if="$t('chapter03.nextChapterPath')"
          :to="`/${locale}/${$t('chapter03.nextChapterPath')}`"
          :text="$t('chapter03.nextChapterText')"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { BackButton, NextPageButton } from '@/components'
import styles from './styles.module.css'
import WhySection from './components/WhySection/index.vue'
import CloneSection from './components/CloneSection/index.vue'
import EnvConfigSection from './components/EnvConfigSection/index.vue'
import IPPortSection from './components/IPPortSection/index.vue'
import DataPathSection from './components/DataPathSection/index.vue'
import PasswordSection from './components/PasswordSection/index.vue'
import OtherConfigSection from './components/OtherConfigSection/index.vue'
import VerifySection from './components/VerifySection/index.vue'
import DocsSection from './components/DocsSection/index.vue'
import NextStepsSection from './components/NextStepsSection/index.vue'

const { locale } = useI18n()
</script>
