// servers/frontend/src/pages/Chapter04Page/components/CommonOperationsSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { tList } from "@/utils/i18nContent";


const CommonOperationsSection = memo(() => {
  const { t } = useTranslation("chapter04");

  return (
    <section>
      <h2>{t("commonOperations.title")}</h2>
      <div>
        <h3>{t("commonOperations.restart.title")}</h3>
        {tList(t, "commonOperations.restart.commands").map((cmd, index) => (
          <pre key={index}>
            <code>{cmd}</code>
          </pre>
        ))}
      </div>
      <div>
        <h3>{t("commonOperations.stop.title")}</h3>
        {tList(t, "commonOperations.stop.commands").map((cmd, index) => (
          <pre key={index}>
            <code>{cmd}</code>
          </pre>
        ))}
      </div>
      <div>
        <h3>{t("commonOperations.update.title")}</h3>
        {tList(t, "commonOperations.update.commands").map((cmd, index) => (
          <pre key={index}>
            <code>{cmd}</code>
          </pre>
        ))}
      </div>
      <div>
        <h3>{t("commonOperations.updateContent.title")}</h3>
        <p>{t("commonOperations.updateContent.description")}</p>
        <pre>
          <code>{t("commonOperations.updateContent.command")}</code>
        </pre>
      </div>
      <div>
        <h3>{t("commonOperations.viewStatus.title")}</h3>
        {tList(t, "commonOperations.viewStatus.commands").map((cmd, index) => (
          <pre key={index}>
            <code>{cmd}</code>
          </pre>
        ))}
      </div>
    </section>
  );
});

CommonOperationsSection.displayName = "CommonOperationsSection";
export default CommonOperationsSection;

// servers/frontend/src/pages/Chapter04Page/components/CommonOperationsSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter04.commonOperations.title') }}</h2>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.commonOperations.restart.title') }}</h3>
      <pre v-for="(cmd, index) in $tm('chapter04.commonOperations.restart.commands')" :key="index"><code>{{ cmd }}</code></pre>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.commonOperations.stop.title') }}</h3>
      <pre v-for="(cmd, index) in $tm('chapter04.commonOperations.stop.commands')" :key="index"><code>{{ cmd }}</code></pre>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.commonOperations.update.title') }}</h3>
      <pre v-for="(cmd, index) in $tm('chapter04.commonOperations.update.commands')" :key="index"><code>{{ cmd }}</code></pre>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.commonOperations.updateContent.title') }}</h3>
      <p>{{ $t('chapter04.commonOperations.updateContent.description') }}</p>
      <pre><code>{{ $t('chapter04.commonOperations.updateContent.command') }}</code></pre>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.commonOperations.viewStatus.title') }}</h3>
      <pre v-for="(cmd, index) in $tm('chapter04.commonOperations.viewStatus.commands')" :key="index"><code>{{ cmd }}</code></pre>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
