// servers/frontend/src/pages/RepoPage/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";
import { Card, Container, Flex, Grid, Heading, Text } from "nfx-ui/components";
import { PageFrame } from "nfx-ui/layouts";

const RepoPage = memo(() => {
  const { t } = useTranslation("repo");

  const repos = [
    {
      name: "NFX-Stack",
      description: t("nfxStack.description"),
      url: "https://github.com/NebulaForgeX/NFX-Stack",
      language: "Docker Compose",
    },
    {
      name: "NFX-Edge",
      description: t("nfxEdge.description"),
      url: "https://github.com/NebulaForgeX/NFX-Edge",
      language: "Docker Compose",
    },
    {
      name: "NFX-Vault",
      description: t("nfxVault.description"),
      url: "https://github.com/NebulaForgeX/NFX-Vault",
      language: "Python / React",
    },
    {
      name: "NFX-Documentation",
      description: t("nfxDocumentation.description"),
      url: "https://github.com/NebulaForgeX/NFX-Documentation",
      language: "React / TypeScript",
    },
    {
      name: "NFX-UI",
      description: t("nfxUi.description"),
      url: "https://github.com/NebulaForgeX/NFX-UI",
      language: "React / TypeScript",
    },
    {
      name: "NFX-News",
      description: t("nfxNews.description"),
      url: "https://github.com/NebulaForgeX/NFX-News",
      language: "Python / TypeScript",
    },
    {
      name: "NFX-Identity",
      description: t("nfxIdentity.description"),
      url: "https://github.com/NebulaForgeX/NFX-Identity",
      language: "Go",
    },
  ];

  return (
    <PageFrame>
      <Container size="3" py="6">
        <Flex direction="column" gap="5">
          <Flex direction="column" gap="2">
            <Heading size="8">{t("title")}</Heading>
            <Text as="p" size="4" color="gray">
              {t("description")}
            </Text>
          </Flex>
          <Grid columns={{ initial: "1", sm: "2" }} gap="4">
            {repos.map((repo) => (
              <Card asChild key={repo.name}>
                <a href={repo.url} target="_blank" rel="noopener noreferrer">
                  <Flex direction="column" gap="2">
                    <Heading size="4">{repo.name}</Heading>
                    <Text as="p" size="2" color="gray">
                      {repo.description}
                    </Text>
                    <Text size="1" color="gray">
                      {repo.language}
                    </Text>
                  </Flex>
                </a>
              </Card>
            ))}
          </Grid>
        </Flex>
      </Container>
    </PageFrame>
  );
});

RepoPage.displayName = "RepoPage";
export default RepoPage;

// servers/frontend/src/pages/RepoPage/index.vue
<template>
  <div :class="styles.container">
    <header :class="styles.header">
      <h1>{{ $t('repo.title') }}</h1>
      <p>{{ $t('repo.description') }}</p>
    </header>

    <div :class="styles.repoList">
      <a
        v-for="repo in repos"
        :key="repo.name"
        :href="repo.url"
        target="_blank"
        rel="noopener noreferrer"
        :class="styles.repoCard"
      >
        <div :class="styles.repoHeader">
          <svg :class="styles.repoIcon" fill="currentColor" viewBox="0 0 24 24">
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
          </svg>
          <h3 :class="styles.repoTitle">{{ repo.name }}</h3>
        </div>
        <p :class="styles.repoDescription">{{ repo.description }}</p>
        <div :class="styles.repoFooter">
          <span>{{ repo.language }}</span>
        </div>
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import styles from './styles.module.css'

const { t } = useI18n()

const repos = computed(() => [
  {
    name: 'NFX-Stack',
    description: t('repo.nfxStack.description'),
    url: 'https://github.com/NebulaForgeX/NFX-Stack',
    language: 'Docker Compose',
  },
  {
    name: 'NFX-Edge',
    description: t('repo.nfxEdge.description'),
    url: 'https://github.com/NebulaForgeX/NFX-Edge',
    language: 'Docker Compose',
  },
  {
    name: 'NFX-Vault',
    description: t('repo.nfxVault.description'),
    url: 'https://github.com/NebulaForgeX/NFX-Vault',
    language: 'Python / React',
  },
  {
    name: 'NFX-Documentation',
    description: t('repo.nfxDocumentation.description'),
    url: 'https://github.com/NebulaForgeX/NFX-Documentation',
    language: 'Vue',
  },
  {
    name: 'NFX-UI',
    description: t('repo.nfxUi.description'),
    url: 'https://github.com/NebulaForgeX/NFX-UI',
    language: 'React / TypeScript',
  },
  {
    name: 'NFX-News',
    description: t('repo.nfxNews.description'),
    url: 'https://github.com/NebulaForgeX/NFX-News',
    language: 'Python / TypeScript',
  },
  {
    name: 'NFX-Identity',
    description: t('repo.nfxIdentity.description'),
    url: 'https://github.com/NebulaForgeX/NFX-Identity',
    language: 'Go',
  },
])
</script>
