// servers/frontend/src/pages/Chapter04Page/components/WhySection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter04.why.title') }}</h2>
    <p>{{ $t('chapter04.why.description') }}</p>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.why.unifiedEntry.title') }}</h3>
      <p>{{ $t('chapter04.why.unifiedEntry.description') }}</p>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.why.httpsSupport.title') }}</h3>
      <p>{{ $t('chapter04.why.httpsSupport.description') }}</p>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.why.certificateUsage.title') }}</h3>
      <p v-html="$t('chapter04.why.certificateUsage.description')"></p>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.why.multiSiteManagement.title') }}</h3>
      <p>{{ $t('chapter04.why.multiSiteManagement.description') }}</p>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.why.easyDeployment.title') }}</h3>
      <p>{{ $t('chapter04.why.easyDeployment.description') }}</p>
    </div>

    <div :class="styles.subsection">
      <h3>{{ $t('chapter04.why.productionOptimization.title') }}</h3>
      <p>{{ $t('chapter04.why.productionOptimization.description') }}</p>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter04Page/components/WhySection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


const WhySection = memo(() => {
  const { t } = useTranslation("chapter04");

  return (
    <section>
      <h2>{t("why.title")}</h2>
      <p>{t("why.description")}</p>
      <div>
        <h3>{t("why.unifiedEntry.title")}</h3>
        <p>{t("why.unifiedEntry.description")}</p>
      </div>
      <div>
        <h3>{t("why.httpsSupport.title")}</h3>
        <p>{t("why.httpsSupport.description")}</p>
      </div>
      <div>
        <h3>{t("why.certificateUsage.title")}</h3>
        <p dangerouslySetInnerHTML={{ __html: t("why.certificateUsage.description") }} />
      </div>
      <div>
        <h3>{t("why.multiSiteManagement.title")}</h3>
        <p>{t("why.multiSiteManagement.description")}</p>
      </div>
      <div>
        <h3>{t("why.easyDeployment.title")}</h3>
        <p>{t("why.easyDeployment.description")}</p>
      </div>
      <div>
        <h3>{t("why.productionOptimization.title")}</h3>
        <p>{t("why.productionOptimization.description")}</p>
      </div>
    </section>
  );
});

WhySection.displayName = "WhySection";
export default WhySection;
