// servers/frontend/src/pages/Chapter04Page/components/VerifyConfigSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";

import { tList, tObject } from "@/utils/i18nContent";


const VerifyConfigSection = memo(() => {
  const { t } = useTranslation("chapter04");
  const portCheck = tObject(t, "verifyConfig.portCheck");

  return (
    <section>
      <h2>{t("verifyConfig.title")}</h2>
      <p>{t("verifyConfig.description")}</p>
      <ul>
        {tList(t, "verifyConfig.checks").map((check, index) => (
          <li key={index} dangerouslySetInnerHTML={{ __html: check }} />
        ))}
      </ul>
      {portCheck ? (
        <div>
          <h3>{t("verifyConfig.portCheck.title")}</h3>
          <pre>
            <code>{t("verifyConfig.portCheck.command")}</code>
          </pre>
          <p>{t("verifyConfig.portCheck.note")}</p>
        </div>
      ) : null}
    </section>
  );
});

VerifyConfigSection.displayName = "VerifyConfigSection";
export default VerifyConfigSection;

// servers/frontend/src/pages/Chapter04Page/components/VerifyConfigSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter04.verifyConfig.title') }}</h2>
    <p>{{ $t('chapter04.verifyConfig.description') }}</p>

    <ul>
      <li v-for="(check, index) in $tm('chapter04.verifyConfig.checks')" :key="index" v-html="check"></li>
    </ul>

    <div :class="styles.subsection" v-if="$t('chapter04.verifyConfig.portCheck')">
      <h3>{{ $t('chapter04.verifyConfig.portCheck.title') }}</h3>
      <pre><code>{{ $t('chapter04.verifyConfig.portCheck.command') }}</code></pre>
      <p>{{ $t('chapter04.verifyConfig.portCheck.note') }}</p>
    </div>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
