// servers/frontend/src/pages/Chapter03Page/components/WhySection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const WhySection = memo(() => {
  const { t } = useTranslation("chapter03");

  return (
      <section>
          <h2>{t("why.title")}</h2>
          <p>{t("why.description")}</p>
          <ul>
            {tList(t, "why.items").map((item, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
          </ul>
        </section>
  );
});

WhySection.displayName = "WhySection";
export default WhySection;

// servers/frontend/src/pages/Chapter03Page/components/WhySection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter03.why.title') }}</h2>
    <p>{{ $t('chapter03.why.description') }}</p>
    <ul>
      <li v-for="(item, index) in $tm('chapter03.why.items')" :key="index" v-html="item"></li>
    </ul>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
