// servers/frontend/src/pages/Chapter05Page/components/NextStepsSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter05.nextSteps.title') }}</h2>
    <p>{{ $t('chapter05.nextSteps.description') }}</p>
    <p>{{ $t('chapter05.nextSteps.description2') }}</p>
    <p v-html="$t('chapter05.nextSteps.conclusion')"></p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>

// servers/frontend/src/pages/Chapter05Page/components/NextStepsSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


const NextStepsSection = memo(() => {
  const { t } = useTranslation("chapter05");

  return (
    <section>
      <h2>{t("nextSteps.title")}</h2>
      <p>{t("nextSteps.description")}</p>
      <p>{t("nextSteps.description2")}</p>
      <p dangerouslySetInnerHTML={{ __html: t("nextSteps.conclusion") }} />
    </section>
  );
});

NextStepsSection.displayName = "NextStepsSection";
export default NextStepsSection;
