// servers/frontend/src/pages/Chapter03Page/components/NextStepsSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


import { tList } from "@/utils/i18nContent";

const NextStepsSection = memo(() => {
  const { t } = useTranslation("chapter03");

  return (
      <section>
          <h2>{t("nextSteps.title")}</h2>
          <p>{t("nextSteps.description")}</p>
          <ol>
            {tList(t, "nextSteps.items").map((item, index) => (
                <li key={index} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
          </ol>
          <p dangerouslySetInnerHTML={{ __html: t("nextSteps.conclusion") }} />
        </section>
  );
});

NextStepsSection.displayName = "NextStepsSection";
export default NextStepsSection;

// servers/frontend/src/pages/Chapter03Page/components/NextStepsSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter03.nextSteps.title') }}</h2>
    <p>{{ $t('chapter03.nextSteps.description') }}</p>
    <ol>
      <li v-for="(item, index) in $tm('chapter03.nextSteps.items')" :key="index" v-html="item"></li>
    </ol>
    <p v-html="$t('chapter03.nextSteps.conclusion')"></p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
