// servers/frontend/src/pages/Chapter05Page/components/StartServiceSection/index.tsx
import { memo } from "react";
import { useTranslation } from "react-i18next";


const StartServiceSection = memo(() => {
  const { t } = useTranslation("chapter05");

  return (
    <section>
      <h2>{t("startService.title")}</h2>
      <p>{t("startService.description")}</p>
      <pre>
        <code>{t("startService.command")}</code>
      </pre>
      <p>{t("startService.description2")}</p>
      <p>{t("startService.description3")}</p>
      <p>{t("startService.description4")}</p>
      <p>{t("startService.description5")}</p>
    </section>
  );
});

StartServiceSection.displayName = "StartServiceSection";
export default StartServiceSection;

// servers/frontend/src/pages/Chapter05Page/components/StartServiceSection/index.vue
<template>
  <section :class="styles.section">
    <h2>{{ $t('chapter05.startService.title') }}</h2>
    <p>{{ $t('chapter05.startService.description') }}</p>
    <pre><code>{{ $t('chapter05.startService.command') }}</code></pre>
    <p>{{ $t('chapter05.startService.description2') }}</p>
    <p>{{ $t('chapter05.startService.description3') }}</p>
    <p>{{ $t('chapter05.startService.description4') }}</p>
    <p>{{ $t('chapter05.startService.description5') }}</p>
  </section>
</template>

<script setup lang="ts">
import styles from './styles.module.css'
</script>
